default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 25
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

test:
  <<: *default
  reconnect: false
  pool: 5
  database: rpg_test
  socket: /tmp/mysql.sock

acceptance:
  <<: *default

production:
  <<: *default
